- name: Create stack user
  user: name=stack
        state=present
        password="stck4/10"
  sudo: yes

- name: Add stack to sudoers
  shell: echo "stack ALL=(root) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/stack && sudo chmod 0440 /etc/sudoers.d/stack
  args:
    creates: /etc/sudoers.d/stack
  sudo: yes

- name: Install git
  yum: name=git state=latest
  sudo: yes

- name: Install iptables
  yum: name=iptables state=latest
  sudo: yes

- name: Install iptables-services
  yum: name=iptables-services state=latest
  sudo: yes

- name: Start iptables
  service: name=iptables enabled=yes state=started
  sudo: yes

- name: Install epel-release
  yum: name=epel-release state=latest
  sudo: yes

- name: Install pip
  yum: name=python-pip state=latest
  sudo: yes

- name: Install tox
  pip: name=tox state=latest
  sudo: yes

# virtualenv bundles its own copy of pip and setuptools which are then used by
# tox. Older versions wont work with some OpenStack requirements such as pbr.
# If there is somehow a version of virtualenv installed already, the install of
# tox above wont install the latest, so we ensure that here.
- name: Update virtualenv
  command: pip install -IU virtualenv
  sudo: yes
