- name: Clone tripleo-common repository
  git: repo=https://git.openstack.org/openstack/tripleo-common
       dest={{ tripleo_common_directory }}
       update=no
  become: yes
  become_user: stack

- name: Checkout patch "Initial Integration of Mistral into TripleO"
  shell: git fetch https://review.openstack.org/openstack/tripleo-common refs/changes/66/282366/29 && git checkout FETCH_HEAD
  args:
    chdir: "{{ tripleo_common_directory }}"
    creates: "{{ tripleo_common_directory }}/tripleo_common/actions/__init__.py"
  become: yes
  become_user: stack
