- name: Create tripleo.conf
  shell: cp "{{ tripleo_common_directory }}/etc/tripleo/tripleo.conf.sample" "{{ tripleo_common_directory }}/tripleo.conf"
  args:
    creates: "{{ tripleo_common_directory }}/tripleo.conf" 
  become: yes
  become_user: stack

- name: Set cors allowed_origin in tripleo.conf
  ini_file: dest="{{ tripleo_common_directory }}/tripleo.conf" section=cors option=allowed_origin value=*
  become: yes
  become_user: stack

- name: Set cors allow_methods in tripleo.conf
  ini_file: dest="{{ tripleo_common_directory }}/tripleo.conf" section=cors option=allow_methods value=GET,POST,PATCH,PUT,DELETE,OPTIONS
  become: yes
  become_user: stack

- name: Set cors allow_headers in tripleo.conf
  ini_file: dest="{{ tripleo_common_directory }}/tripleo.conf" section=cors option=allow_headers value=Content-Type,Cache-Control,Content-Language,Expires,Last-Modified,Pragma,X-Auth-Token
  become: yes
  become_user: stack

- name: Read keystone password from undercloud-passwords.conf
  shell: grep undercloud_admin_password /home/stack/undercloud-passwords.conf | awk -F = '{print $2}'
  register: undercloud_admin_password
  become: yes
  become_user: stack

- name: Set keystone password in tripleo.conf
  ini_file: dest="{{ tripleo_common_directory }}/tripleo.conf" section=keystone option=password value="{{ undercloud_admin_password.stdout }}"
  become: yes
  become_user: stack

- name: Set keystone auth_url in tripleo.conf
  ini_file: dest="{{ tripleo_common_directory }}/tripleo.conf" section=keystone option=auth_url value=http://192.0.2.1:35357/v2.0
  become: yes
  become_user: stack
